version: "3.9"

services:
  angular-app:
    build: .
    container_name: adoption-animal-app
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    networks:
      - controlimage_network
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro  # monta certificados do host

networks:
  controlimage_network:
    external: true
