events {}

http {
  include       mime.types;
  default_type  application/octet-stream;

  server {
    listen 80;
    server_name animal-adoption.com.br;
    return 301 https://$host$request_uri;
  }

  server {
    listen 443 ssl;
    server_name animal-adoption.com.br;

    root /usr/share/nginx/html;
    index index.html;

    location / {
      try_files $uri $uri/ /index.html;
    }

    location /api/ {
      proxy_pass http://api_animal_adoption:8081/api/;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-For $remote_addr;
      proxy_set_header X-Forwarded-Proto https;
    }

    location /public/ {
      proxy_pass http://api_animal_adoption:8081/public/;
    }

    location /images/ {
      proxy_pass http://image-api:8082/images/;
    }
  }
}
